import type { Metadata } from "next";
import localFont from "next/font/local";
import "@/app/globals.css";
import StarBackground from "@/components/shared/StarBackground";

const cloickSans = localFont({
  src: "../fonts/Cloick.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${cloickSans.variable} antialiased`}
      >
        <StarBackground>
          {children}
        </StarBackground>
      </body>
    </html>
  );
}
